services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp

    ports:
      - "1935:1935"  # Exponer el puerto RTMP
      - "8080:8080"  # Exponer el puerto HTTP (para HLS si se usa)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - streaming

  ffmpeg:
    image: jrottenberg/ffmpeg:latest
    entrypoint: >
      sh -c "ffmpeg -re -stream_loop -1 -i /usr/share/nginx/html/input.mp4 -c:v libx264 -b:v 5000k -s 1920x1080 -c:a aac -b:a 128k -f flv rtmp://10.31.101.254/live/test && tail -f /dev/null"
    volumes:
      - /home/<user>/nginx-rtmp-dc/video:/usr/share/nginx/html
    networks:
      - streaming
    restart: always   
    depends_on:
      - nginx-rtmp

networks:
  streaming:
    external: true
    